spring.application.name=JAVA
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.security.oauth2.client.registration.github.client-id=Ov23li5lWifRdHQfujgj
spring.security.oauth2.client.registration.github.client-secret=cf21e25b768f155a715e7fe0843846f9426c4c1c
spring.security.oauth2.client.registration.github.scope=read:user,user:email